---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'quay.io/ansible/ansible-runner:latest'

dependencies:
  python: requirements.txt

additional_build_steps:
  prepend:
    - RUN yum -y update && yum -y upgrade && yum clean all && rm -rf /var/cache/yum
    - RUN /usr/bin/python3 -m pip install --upgrade pip --no-cache-dir
  append:
    - RUN ansible-galaxy collection install community.general -p /usr/share/ansible/collections
    - RUN rm -rf /root/.cache/pip/*
    - RUN pip3 list installed
